name: cli_wrapper
description:
  A tool package for developing flutter or dart cli.
  Use cli_wrapper to wrap a cli with more advanced usage.
version: 0.5.0
homepage: https://github.com/hyiso/cli.dart
repository: https://github.com/hyiso/cli.dart/tree/main/packages/cli_wrapper

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
